export type StructureCategory =
  | 'Storytelling'
  | 'Marketing'
  | 'Business insight'
  | 'Productivité'
  | 'Leadership'
  | 'Personal brand'
  | 'Vente';

export type LinkedInStructure = {
  id: string;
  name: string;
  description: string;
  structure: string;
  category: StructureCategory;
};

export const LINKEDIN_STRUCTURES: LinkedInStructure[] = [
  {
    id: 'hook-polemique',
    name: 'Hook polémique',
    description: 'Casse une idée reçue pour capter l\'attention',
    category: 'Business insight',
    structure: 'Hook qui casse une idée reçue → Observation → Explication → Insight → CTA',
  },
  {
    id: 'story-personnelle',
    name: 'Story personnelle',
    description: 'Récit vécu qui inspire et crée connexion',
    category: 'Storytelling',
    structure: 'Hook → Situation → Problème → Découverte → Leçon → CTA',
  },
  {
    id: 'liste-erreurs',
    name: 'Liste d\'erreurs',
    description: 'Les erreurs à éviter, très partagé',
    category: 'Marketing',
    structure: 'Hook → Problème → 3 erreurs fréquentes → Solution → CTA',
  },
  {
    id: 'comparaison',
    name: 'Comparaison',
    description: 'Avant/après ou deux approches contrastées',
    category: 'Business insight',
    structure: 'Hook → Comparaison entre deux approches → Analyse → Conclusion → CTA',
  },
  {
    id: 'etude-de-cas',
    name: 'Étude de cas',
    description: 'Cas concret avec résultats mesurables',
    category: 'Business insight',
    structure: 'Hook → Contexte → Action réalisée → Résultat → Conclusion → CTA',
  },
  {
    id: 'insight-business',
    name: 'Insight business',
    description: 'Observation surprenante sur le business',
    category: 'Business insight',
    structure: 'Hook → Observation → Explication → Exemple → Conclusion → CTA',
  },
  {
    id: 'mythe-deconstruire',
    name: 'Mythe à déconstruire',
    description: 'Contredit une croyance populaire',
    category: 'Business insight',
    structure: 'Hook → Croyance populaire → Pourquoi c\'est faux → Nouvelle perspective → Conclusion → CTA',
  },
  {
    id: 'mini-guide',
    name: 'Mini guide',
    description: 'Conseils actionnables en liste',
    category: 'Marketing',
    structure: 'Hook → Annonce du guide → 3 à 5 conseils → Conclusion → CTA',
  },
  {
    id: 'le-declic',
    name: 'Le déclic',
    description: 'Moment de prise de conscience transformateur',
    category: 'Storytelling',
    structure: 'Hook → Situation initiale → Moment de prise de conscience → Changement → Leçon → CTA',
  },
  {
    id: 'question-provocatrice',
    name: 'Question provocatrice',
    description: 'Question qui fait réfléchir et commenter',
    category: 'Leadership',
    structure: 'Question → Réflexion → Insight → Conclusion → CTA',
  },
  {
    id: 'avant-apres',
    name: 'Avant / Après',
    description: 'Transformation concrète',
    category: 'Storytelling',
    structure: 'Hook → Situation avant → Ce qui a changé → Résultat après → Leçon → CTA',
  },
  {
    id: 'lecon-echec',
    name: 'Leçon d\'un échec',
    description: 'Vulnérabilité et apprentissage',
    category: 'Personal brand',
    structure: 'Hook → Contexte de l\'échec → Ce que j\'ai appris → Application → CTA',
  },
  {
    id: 'prediction',
    name: 'Prédiction',
    description: 'Ose prédire une tendance',
    category: 'Business insight',
    structure: 'Hook → Tendance observée → Pourquoi ça va s\'amplifier → Conséquences → CTA',
  },
  {
    id: 'conseil-counter-intuitif',
    name: 'Conseil contre-intuitif',
    description: 'Inverse les attentes',
    category: 'Business insight',
    structure: 'Hook → Ce que font la plupart → Pourquoi ça ne marche pas → Alternative → CTA',
  },
  {
    id: 'chiffre-choc',
    name: 'Chiffre choc',
    description: 'Statistique qui interpelle',
    category: 'Marketing',
    structure: 'Hook (chiffre) → Contexte → Explication → Implications → CTA',
  },
  {
    id: 'histoire-client',
    name: 'Histoire client',
    description: 'Témoignage ou cas client',
    category: 'Vente',
    structure: 'Hook → Qui est le client → Problème → Solution apportée → Résultat → CTA',
  },
  {
    id: 'framework',
    name: 'Framework / Méthode',
    description: 'Structure réutilisable avec sigle',
    category: 'Productivité',
    structure: 'Hook → Présentation du framework → Point 1 → Point 2 → Point 3 → Conclusion → CTA',
  },
  {
    id: 'ce-que-personne-ne-dit',
    name: 'Ce que personne ne dit',
    description: 'Angle non exploré',
    category: 'Business insight',
    structure: 'Hook → Sujet tabou ou ignoré → Pourquoi → La vérité → CTA',
  },
  {
    id: 'journee-type',
    name: 'Ma journée type',
    description: 'Backstage et authenticité',
    category: 'Personal brand',
    structure: 'Hook → Matin → Midi → Après-midi → Leçon du quotidien → CTA',
  },
  {
    id: 'contraste-generations',
    name: 'Contraste générations',
    description: 'Différences Boomer / Gen Z etc.',
    category: 'Leadership',
    structure: 'Hook → Génération A fait X → Génération B fait Y → Ce qu\'on peut apprendre → CTA',
  },
  {
    id: 'confession',
    name: 'Confession',
    description: 'Admet une faiblesse ou erreur',
    category: 'Personal brand',
    structure: 'Hook → Ce que je cachais → Pourquoi c\'est libérateur → Nouvelle approche → CTA',
  },
  {
    id: '3-idees-recues',
    name: '3 idées reçues',
    description: 'Démontage en série',
    category: 'Marketing',
    structure: 'Hook → Idée reçue 1 + vérité → Idée reçue 2 + vérité → Idée reçue 3 + vérité → CTA',
  },
  {
    id: 'si-vous-avez-1h',
    name: 'Si vous avez 1 h',
    description: 'Conseil condensé',
    category: 'Productivité',
    structure: 'Hook → Contexte (peu de temps) → La chose à faire → Pourquoi → CTA',
  },
  {
    id: 'ce-que-j-aurais-voulu-savoir',
    name: 'Ce que j\'aurais voulu savoir',
    description: 'Sagesse rétrospective',
    category: 'Leadership',
    structure: 'Hook → Il y a X ans → Ce que je sais maintenant → Impact → CTA',
  },
  {
    id: 'pourquoi-personne-ne',
    name: 'Pourquoi personne ne...',
    description: 'Question qui intrigue',
    category: 'Business insight',
    structure: 'Hook (question) → Réponse surprise → Explication → Conséquence → CTA',
  },
  {
    id: 'template-replicable',
    name: 'Template réplicable',
    description: 'Donne un modèle à appliquer',
    category: 'Productivité',
    structure: 'Hook → Template en X étapes → Exemple rapide → Invitation à essayer → CTA',
  },
  {
    id: 'debunk',
    name: 'Debunk',
    description: 'Démontage d\'une affirmation',
    category: 'Business insight',
    structure: 'Hook → L\'affirmation → Preuve du contraire → La réalité → CTA',
  },
  {
    id: 'meme-business',
    name: 'Même business, approches différentes',
    description: 'Comparaison de stratégies',
    category: 'Marketing',
    structure: 'Hook → Entreprise A → Entreprise B → Ce qui explique la différence → CTA',
  },
  {
    id: 'symptome-cause',
    name: 'Symptôme vs cause',
    description: 'Distinguer surface et profondeur',
    category: 'Leadership',
    structure: 'Hook → Le symptôme (ce qu\'on voit) → La cause réelle → Solution → CTA',
  },
  {
    id: 'promesse-resultat',
    name: 'Promesse + résultat',
    description: 'Annonce une révélation',
    category: 'Vente',
    structure: 'Hook (promesse) → Contexte → La révélation → Preuve/Bénéfice → CTA',
  },
  {
    id: 'letter-to-younger-self',
    name: 'Lettre à mon moi du passé',
    description: 'Conseils à soi-même',
    category: 'Personal brand',
    structure: 'Hook → Ce que je dirais → Conseil 1 → Conseil 2 → Conseil 3 → CTA',
  },
  {
    id: 'red-flags',
    name: 'Red flags',
    description: 'Signaux d\'alerte',
    category: 'Leadership',
    structure: 'Hook → Red flag 1 → Red flag 2 → Red flag 3 → Comment réagir → CTA',
  },
  {
    id: 'green-flags',
    name: 'Green flags',
    description: 'Signaux positifs',
    category: 'Leadership',
    structure: 'Hook → Green flag 1 → Green flag 2 → Green flag 3 → Pourquoi ça compte → CTA',
  },
  {
    id: 'un-seul-conseil',
    name: 'Un seul conseil',
    description: 'Focus sur l\'essentiel',
    category: 'Productivité',
    structure: 'Hook → Le conseil → Pourquoi c\'est le plus important → Application → CTA',
  },
  {
    id: 'ce-qui-a-change',
    name: 'Ce qui a tout changé',
    description: 'Point de bascule',
    category: 'Storytelling',
    structure: 'Hook → Avant → L\'élément déclencheur → Après → Leçon → CTA',
  },
  {
    id: 'question-reponse',
    name: 'Question / Réponse',
    description: 'Format FAQ',
    category: 'Marketing',
    structure: 'Hook (question) → Réponse courte → Développement → Exemple → CTA',
  },
  {
    id: 'ce-que-les-experts-oublient',
    name: 'Ce que les experts oublient',
    description: 'Angle expert mais accessible',
    category: 'Business insight',
    structure: 'Hook → Ce que disent les experts → Ce qu\'ils oublient → La complète vérité → CTA',
  },
  {
    id: 'rituel-quotidien',
    name: 'Mon rituel quotidien',
    description: 'Habits et routines',
    category: 'Productivité',
    structure: 'Hook → Rituel 1 → Rituel 2 → Rituel 3 → Impact → CTA',
  },
  {
    id: 'fausse-bonne-idee',
    name: 'Fausse bonne idée',
    description: 'Ce qui semble bien mais ne l\'est pas',
    category: 'Business insight',
    structure: 'Hook → L\'idée populaire → Pourquoi elle semble bonne → Pourquoi elle échoue → Alternative → CTA',
  },
  {
    id: 'conversation',
    name: 'Conversation fictive',
    description: 'Dialogue éducatif',
    category: 'Vente',
    structure: 'Hook → Échange (question/réponse) → Insight tiré → Application → CTA',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Évolution dans le temps',
    category: 'Storytelling',
    structure: 'Hook → Il y a 5 ans → Il y a 2 ans → Aujourd\'hui → Leçon → CTA',
  },
  {
    id: 'mythe-numero',
    name: 'Mythe #1, #2, #3',
    description: 'Série de mythes',
    category: 'Marketing',
    structure: 'Hook → Mythe 1 + réalité → Mythe 2 + réalité → Mythe 3 + réalité → CTA',
  },
  {
    id: 'si-vous-saviez',
    name: 'Si vous saviez',
    description: 'Révélation qui change la donne',
    category: 'Business insight',
    structure: 'Hook → Ce que la plupart ignorent → Impact de le savoir → Comment l\'utiliser → CTA',
  },
  {
    id: 'erreur-couteuse',
    name: 'L\'erreur qui m\'a coûté cher',
    description: 'Coût de l\'ignorance',
    category: 'Personal brand',
    structure: 'Hook → L\'erreur → Les conséquences → Ce que j\'ai fait → Leçon → CTA',
  },
  {
    id: 'sous-estime',
    name: 'Ce qu\'on sous-estime',
    description: 'Élément négligé',
    category: 'Leadership',
    structure: 'Hook → L\'élément sous-estimé → Pourquoi c\'est crucial → Comment le prendre en compte → CTA',
  },
  {
    id: 'formule-secrete',
    name: 'La formule',
    description: 'Équation ou process',
    category: 'Productivité',
    structure: 'Hook → Présentation de la formule → Composante 1 → Composante 2 → Composante 3 → CTA',
  },
  {
    id: 'ce-que-je-ferais',
    name: 'Ce que je ferais à votre place',
    description: 'Conseil direct',
    category: 'Vente',
    structure: 'Hook → Étape 1 → Étape 2 → Étape 3 → Résultat attendu → CTA',
  },
  {
    id: 'comparaison-attentes-realite',
    name: 'Attentes vs réalité',
    description: 'Écart entre théorie et pratique',
    category: 'Storytelling',
    structure: 'Hook → Ce que j\'imaginais → La réalité → Ce que j\'ai appris → CTA',
  },
  {
    id: 'moment-genant',
    name: 'Moment gênant',
    description: 'Anecdote relatable',
    category: 'Personal brand',
    structure: 'Hook → Le moment → Réaction → Ce que j\'en ai tiré → CTA',
  },
  {
    id: 'pourquoi-j-arrete',
    name: 'Pourquoi j\'arrête de...',
    description: 'Changement de pratique',
    category: 'Leadership',
    structure: 'Hook → Ce que je faisais → Pourquoi j\'arrête → Ce que je fais à la place → CTA',
  },
];

export const STRUCTURE_CATEGORIES: StructureCategory[] = [
  'Storytelling',
  'Marketing',
  'Business insight',
  'Productivité',
  'Leadership',
  'Personal brand',
  'Vente',
];
